### PR TITLE
Make sure _lock exists during write()

### LINKED ISSUE #457: type object tqdm has no attribute '_lock'
Hello, 

I have been using TQDM for quite a while now with a lot of pleasure. However after running a python script this morning, TQDM has started to generate a error and cannot write anything anymore. I have tried to resolve the issue by reinstalling tqdm without succes. I couldn't found any solution to this problem, so I hope you guys can give a clue to what the problem is.

OS: MacOSX 10.12
Python 3.6.1 |Anaconda 4.4.0 (x86_64)| (default, May 11 2017, 13:04:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin

$conda list |grep tqdm
tqdm                      4.18.0                    <pip>
tqdm                      4.18.0                     py_0    conda-forge

Code: 
from tqdm import tqdm
tqdm.write("hello")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/john-melle/anaconda/lib/python3.6/site-packages/tqdm/_tqdm.py", line 497, in write
    with cls.external_write_mode(file=file, nolock=nolock):
  File "/Users/john-melle/anaconda/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/Users/john-melle/anaconda/lib/python3.6/site-packages/tqdm/_tqdm.py", line 512, in external_write_mode
    cls._lock.acquire()
AttributeError: type object 'tqdm' has no attribute '_lock'

### PR DESCRIPTION
**Pull request by mjstevens777**
Fixes #457 caused by #617

### CODE REVIEW

**Comment by casperdcl** [comment]
Thanks @mjstevens777  - I added a unit test as well.
