### ISSUE TITLE
type object tqdm has no attribute '_lock'

### ISSUE THREAD

**Issue by JMBokhorst** [tqdm/tqdm#457]
Hello, 

I have been using TQDM for quite a while now with a lot of pleasure. However after running a python script this morning, TQDM has started to generate a error and cannot write anything anymore. I have tried to resolve the issue by reinstalling tqdm without succes. I couldn't found any solution to this problem, so I hope you guys can give a clue to what the problem is.

OS: MacOSX 10.12
Python 3.6.1 |Anaconda 4.4.0 (x86_64)| (default, May 11 2017, 13:04:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin

$conda list |grep tqdm
tqdm                      4.18.0                    <pip>
tqdm                      4.18.0                     py_0    conda-forge

Code: 
from tqdm import tqdm
tqdm.write("hello")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/john-melle/anaconda/lib/python3.6/site-packages/tqdm/_tqdm.py", line 497, in write
    with cls.external_write_mode(file=file, nolock=nolock):
  File "/Users/john-melle/anaconda/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/Users/john-melle/anaconda/lib/python3.6/site-packages/tqdm/_tqdm.py", line 512, in external_write_mode
    cls._lock.acquire()
AttributeError: type object 'tqdm' has no attribute '_lock'

**Comment by andy-esch** [comment]
I'm getting the same error via my CI: https://travis-ci.org/CartoDB/cartoframes/jobs/282396234#L676-L682

**Comment by casperdcl** [comment]
Sorry about this. The way it's done now, you need to have initialised at least one `tqdm` instance before you can call `tqdm.write`

so 

```python

from tqdm import tqdm
tqdm(disable=True, total=0)  # initialise internal lock
tqdm.write("test")
```

should work.

You could also do

```
from multiprocessing import Lock

tqdm.set_lock(Lock())
```

instead to manually set the internal lock.

Will change this all ASAP to not require any of this.

**Comment by casperdcl** [comment]
Could you try the `devel` branch (commit above) to verify it fixes your problem without altering your code as suggested above?

**Comment by andy-esch** [comment]
Yep, will do!

**Comment by andy-esch** [comment]
After installing the `devel` branch, my tests are running perfectly.

**Comment by casperdcl** [comment]
great, you probably need to put `tqdm!=4.18.0` in your dependencies. Will release 4.18.1 soon

**Comment by andy-esch** [comment]
Nice, thanks for the speedy response. I love tqdm :)

**Comment by JMBokhorst** [comment]
Tests are also running perfectly with the devel branch here! Thanks for the quick response! :)

**Comment by casperdcl** [comment]
fixed in master now

**Comment by asanakoy** [comment]
Still having the same issue with `tqdm 4.19.4`
```
~/.local/lib/python2.7/site-packages/tqdm/_tqdm.pyc in __new__(cls, *args, **kwargs)
    449         if "_instances" not in cls.__dict__:
    450             cls._instances = WeakSet()
--> 451         with cls._lock:
    452             cls._instances.add(instance)
    453         # Create the monitoring thread

AttributeError: type object 'tqdm' has no attribute '_lock'
```

**Comment by casperdcl** [comment]
argh. really

**Comment by casperdcl** [comment]
is this consistently reproducible?

**Comment by asanakoy** [comment]
I have rolled back to 4.17. It's not crashing any more. But before that it crashed every time I used tqdm.tqdm.

**Comment by casperdcl** [comment]
could you check if the current `devel` branch fixes this issue for you?

**Comment by casperdcl** [comment]
@asanakoy ?

**Comment by craig-warren** [comment]
I am experiencing this issue since updating to 4.29.0 and Python 3.7.2 on macOS 10.14.

```
File "/Users/cwarren/miniconda3/envs/gprMax/lib/python3.7/site-packages/tqdm/_tqdm.py", line 540, in external_write_mode
    cls._lock.acquire()
AttributeError: type object 'tqdm' has no attribute '_lock'
```

If I downgrade tqdm to 4.28.1 with the same environment, the issue goes away.

**Comment by casperdcl** [comment]
@mjstevens777 might need a look?

**Comment by mjstevens777** [comment]
I'm sorry, I wasn't aware of that part of the API. I opened a PR.

**Comment by leolivier** [comment]
Hi, experiencing again the same issue in 2024:
AttributeError: type object 'tqdm' has no attribute '_lock'

The whole stacktrace is here:
```
Traceback (most recent call last):
  File "C:\Users\olivier_levillain\AppData\Local\miniconda3\envs\basic-rag\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "C:\DEV\mobahome\devts\ollama-rag\local_rag_app.py", line 65, in <module>
    page()
  File "C:\DEV\mobahome\devts\ollama-rag\local_rag_app.py", line 44, in page
    st.session_state["assistant"] = ChatPDF()
                                    ^^^^^^^^^
  File "C:\DEV\mobahome\devts\ollama-rag\local_rag.py", line 39, in __init__
    embedding_function=FastEmbedEmbeddings(),
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olivier_levillain\AppData\Local\miniconda3\envs\basic-rag\Lib\site-packages\pydantic\v1\main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olivier_levillain\AppData\Local\miniconda3\envs\basic-rag\Lib\site-packages\pydantic\v1\main.py", line 1100, in validate_model
    values = validator(cls_, values)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olivier_levillain\AppData\Local\miniconda3\envs\basic-rag\Lib\site-packages\langchain_community\embeddings\fastembed.py", line 67, in validate_environment
    values["_model"] = TextEmbedding(
                       ^^^^^^^^^^^^^^
  File "C:\Users\olivier_levillain\AppData\Local\miniconda3\envs\basic-rag\Lib\site-packages\fastembed\text\text_embedding.py", line 59, in __init__
    self.model = embedding(model_name, cache_dir, threads, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olivier_levillain\AppData\Local\miniconda3\envs\basic-rag\Lib\site-packages\fastembed\text\onnx_embedding.py", line 183, in __init__
    self._model_dir = self.download_model(self._model_description, self._cache_dir)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olivier_levillain\AppData\Local\miniconda3\envs\basic-rag\Lib\site-packages\fastembed\common\model_management.py", line 189, in download_model
    return Path(cls.download_files_from_huggingface(hf_source, cache_dir=str(cache_dir)))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olivier_levillain\AppData\Local\miniconda3\envs\basic-rag\Lib\site-packages\fastembed\common\model_management.py", line 85, in download_files_from_huggingface
    return snapshot_download(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\olivier_levillain\AppData\Local\miniconda3\envs\basic-rag\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olivier_levillain\AppData\Local\miniconda3\envs\basic-rag\Lib\site-packages\huggingface_hub\_snapshot_download.py", line 308, in snapshot_download
    thread_map(
  File "C:\Users\olivier_levillain\AppData\Local\miniconda3\envs\basic-rag\Lib\site-packages\tqdm\contrib\concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olivier_levillain\AppData\Local\miniconda3\envs\basic-rag\Lib\site-packages\tqdm\contrib\concurrent.py", line 47, in _executor_map
    with ensure_lock(tqdm_class, lock_name=lock_name) as lk:
  File "C:\Users\olivier_levillain\AppData\Local\miniconda3\envs\basic-rag\Lib\contextlib.py", line 144, in __exit__
    next(self.gen)
  File "C:\Users\olivier_levillain\AppData\Local\miniconda3\envs\basic-rag\Lib\site-packages\tqdm\contrib\concurrent.py", line 24, in ensure_lock
    del tqdm_class._lock
        ^^^^^^^^^^^^^^^^
AttributeError: type object 'tqdm' has no attribute '_lock'
```
and the version is 4.66.2
```
(basic-rag) C:\DEV\mobahome\devts\ollama-rag>conda list tqdm
# packages in environment at C:\Users\olivier_levillain\AppData\Local\miniconda3\envs\basic-rag:
#
# Name                    Version                   Build  Channel
tqdm                      4.66.2                   pypi_0    pypi
```
I used the same code on another machine with no issue, but I don't have the version number on this other machine...

**Comment by jaffe-fly** [comment]
same issue
`tqdm                    4.66.2`

the error：
`Exception ignored in: <function tqdm.__del__ at 0x7f7f75e949a0> [1:59:30<00:00, 240kB/s]
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/tqdm/std.py", line 1148, in __del_                _
    self.close()
  File "/root/miniconda3/lib/python3.12/site-packages/tqdm/std.py", line 1275, in close
    self._decr_instances(self)
  File "/root/miniconda3/lib/python3.12/site-packages/tqdm/std.py", line 696, in _decr_i                nstances
    with cls._lock:
         ^^^^^^^^^
AttributeError: type object 'tqdm' has no attribute '_lock'
Exception ignored in: <function tqdm.__del__ at 0x7f7f75e949a0>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/tqdm/std.py", line 1148, in __del_                _
    self.close()
  File "/root/miniconda3/lib/python3.12/site-packages/tqdm/std.py", line 1275, in close
    self._decr_instances(self)
  File "/root/miniconda3/lib/python3.12/site-packages/tqdm/std.py", line 696, in _decr_i                nstances
    with cls._lock:
         ^^^^^^^^^
AttributeError: type object 'tqdm' has no attribute '_lock'
Exception ignored in: <function tqdm.__del__ at 0x7f7f75e949a0>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/tqdm/std.py", line 1148, in __del_                _
    self.close()
  File "/root/miniconda3/lib/python3.12/site-packages/tqdm/std.py", line 1275, in close
    self._decr_instances(self)
  File "/root/miniconda3/lib/python3.12/site-packages/tqdm/std.py", line 696, in _decr_i                nstances
    with cls._lock:
         ^^^^^^^^^
AttributeError: type object 'tqdm' has no attribute '_lock'
Exception ignored in: <function tqdm.__del__ at 0x7f7f75e949a0>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/tqdm/std.py", line 1148, in __del_                _
    self.close()
  File "/root/miniconda3/lib/python3.12/site-packages/tqdm/std.py", line 1275, in close
    self._decr_instances(self)
  File "/root/miniconda3/lib/python3.12/site-packages/tqdm/std.py", line 696, in _decr_i                nstances
    with cls._lock:
         ^^^^^^^^^
AttributeError: type object 'tqdm' has no attribute '_lock'`
