### PR TITLE
fix: drop tqdm._utils re-exports removed from tqdm.utils

### LINKED ISSUE #927: ImportError: cannot import name '_environ_cols_windows'
- [ ] I have marked all applicable categories:
    + [X] exception-raising bug
    + [ ] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [X] I have visited the [source website], and in particular
  read the [known issues]
- [X] I have searched through the [issue tracker] for duplicates
- [X] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=
  [StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

It appears the 4.44.0 release removed `tqdm.utils._environ_cols_windows`, but `tqdm._utils` still imports it.

tqdm version 4.44.0:
```
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tqdm, sys
>>> print(tqdm.__version__, sys.version, sys.platform)
4.44.0 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] linux
>>> import tqdm._utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jlynch/local/suitcase-tiff/venv/lib/python3.6/site-packages/tqdm/_utils.py", line 1, in <module>
    from .utils import CUR_OS, IS_WIN, IS_NIX, RE_ANSI, _range, _unich, _unicode, colorama, WeakSet, _basestring, _OrderedDict, FormatReplace, Comparable, SimpleTextIOWrapper, _is_utf, _supports_unicode, _is_ascii, _environ_cols_wrapper, _environ_cols_windows, _environ_cols_tput, _environ_cols_linux, _term_move_up  # NOQA
ImportError: cannot import name '_environ_cols_windows'
```

tqdm version 4.43.0:
```
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tqdm, sys
>>> print(tqdm.__version__, sys.version, sys.platform)
4.43.0 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] linux
>>> import tqdm._utils
>>> 
```

### PR DESCRIPTION
**Pull request by MohammedAlkindi**
> Replaces #1789, reopened only to correct the source branch name. Same commit (`5f1b624`), same diff, body unchanged.

- [x] I have marked all applicable categories:
    + [x] exception-raising fix
    + [ ] visual output fix
    + [ ] documentation modification
    + [ ] new feature
- [x] If applicable, I have mentioned the relevant/related issue(s)

Less important but also useful:

- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  # 4.70.0 3.13.13 (tags/v3.13.13:01104ce, Apr  7 2026, 19:25:48) [MSC v.1944 64 bit (AMD64)] win32
  ```

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=

---

`import tqdm._utils` raises `ImportError` on the current release. No open issue — I searched the tracker before filing, and the nearest match, #927, is the same breakage from 2020, closed long ago.

```console
$ pip install tqdm==4.70.0 && python -c "import tqdm._utils"
ImportError: cannot import name '_screen_shape_linux' from 'tqdm.utils'

$ pip install tqdm==4.67.1 && python -c "import tqdm._utils"   # warns, then succeeds
```

### Cause

`0de6e96` ("simplify terminal size detection") replaced the platform-specific helpers with a single `os.get_terminal_size()` call and deleted `_screen_shape_linux`, `_screen_shape_tput` and `_screen_shape_windows` from `tqdm/utils.py`. The deprecated `tqdm/_utils.py` shim still re-exports all three, so the module raises on import instead of emitting its `TqdmDeprecationWarning`.

The shim says it "will be removed in tqdm==5.0.0", so it is meant to keep working through 4.x. It worked in 4.67.1, making this a regression from 4.68.0 onwards. It is not platform-specific — the deleted names are absent everywhere.

### Fix

Drop only those three names from the import list. Every other name it re-exports (`CUR_OS`, `IS_NIX`, `IS_WIN`, `RE_ANSI`, `Comparable`, `FormatReplace`, `SimpleTextIOWrapper`, `_environ_cols_wrapper`, `_is_ascii`, `_is_utf`, `_screen_shape_wrapper`, `_supports_unicode`, `_term_move_up`, `colorama`) is still exported by `tqdm.utils`, verified name by name.

This is the same shape of fix as `0229cc6` ("fix import error => deprecation"), which resolved #927 by realigning this exact import list.

I checked the sibling shims too — `tqdm._tqdm`, `tqdm._tqdm_gui`, `tqdm._tqdm_notebook`, `tqdm._tqdm_pandas`, `tqdm._main` and `tqdm._monitor` all import cleanly and are untouched here.

### Test

`tests/tests_utils.py::test_deprecated_utils_shim` imports the shim and asserts the deprecation warning. Nothing in the suite had ever imported `tqdm._utils`, which is why this class of break has now shipped twice; the test closes that gap.

It fails before this change with the `ImportError` above and passes after:

```
$ pytest tests/tests_utils.py::test_deprecated_utils_shim   # before
E   ImportError: cannot import name '_screen_shape_linux' from 'tqdm.utils'
1 failed

$ pytest tests/tests_utils.py                               # after
5 passed
```

Full suite on this branch: **150 passed, 11 skipped, 0 failed**. `flake8`, `isort --check-only` and `pyupgrade --py38-plus` are all clean on the changed files.

### CODE REVIEW

**Comment by MohammedAlkindi** [comment]
For context: this supersedes #1789, which I closed after opening this. Nothing about the change differs — same commit `5f1b624`, same two files.
