### ISSUE TITLE
tqdm can't work with python 2.7

### ISSUE THREAD

**Issue by AlvinChen13** [tqdm/tqdm#350]
I have do 'sudo pip install tqdm', and I try to import tqdm from pytyon, but get failed.
Anyone know what happen?

[alvin@sdx-tf0 speech-to-text-wavenet]$ python
Python 2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from tqdm import tqdm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/tqdm/__init__.py", line 1, in <module>
    from ._tqdm import tqdm
  File "/usr/lib/python2.7/site-packages/tqdm/_tqdm.py", line 14, in <module>
    from ._utils import _supports_unicode, _environ_cols_wrapper, _range, _unich, \
  File "/usr/lib/python2.7/site-packages/tqdm/_utils.py", line 3, in <module>
    from platform import system as _curos
ImportError: cannot import name system
>>>

**Comment by AlvinChen13** [comment]
Fix it by setting PYTHONPATH to empty.
But how could I make it work with my own PYTHONPATH setting?

**Comment by lrq3000** [comment]
Hello AlvinChen13,

I think something is messing with you Python install, because "platform" is
a standard Python library since Python 2.3.

My guess is that you have a python script in your Python install which has
exactly the same name, overshadowing the native Python lib.

You can try to track down the faulty python script by resetting back your
PYTHONPATH to the previous value (non empty), and then type this in a
Python shell:

import platformprint platform.__file__

Then you can either rename this script and place it somewhere else.


2017-02-16 8:05 GMT+01:00 AlvinChen13 <notifications@github.com>:

**Comment by casperdcl** [comment]
Going to close this for now because it seems to be related to a broken python installation. Happy to reopen @AlvinChen13 if you think there's something wrong with `tqdm`. Just to clarify, this should always work:

```sh
$ python -c "import platform; print platform.__file__"
```
